sudo: false
language: node_js
node_js:
  - "stable"
  - "0.10"
  - "0.12"
  - "4"

addons:
  apt:
    sources:
      - "ubuntu-toolchain-r-test"
    packages:
      - "g++-4.8"

env:
  - "CXX=g++-4.8"

before_install:
  - "$CXX --version"
